#!/usr/bin/env bash
#
# JANUS NLI quick smoke-test entry script.
#
# Goal: end-to-end "is the pipeline wired correctly?" run on the new structured
# JANUS dataset (instruction / trajectory_1 / summary / label) — NOT a
# real training run. Defaults are tuned to be small and fast.
#
# Prereqs:
#   1) Run scripts/split_val.py first to produce train_quick.json + val.json:
#        python scripts/split_val.py \
#          --src "/path/to/janus/train/train_converted_part_*.json" \
#          --out_dir /path/to/janus_dataset \
#          --val_per_group 2 --min_per_class 30 --train_cap 1700
#   2) MODEL_PATH points to a local Qwen2.5-7B-Instruct (or similar) checkpoint.
#
# Usage:
#   MODEL_PATH=/local/path/to/qwen2.5-7b-instruct \
#     bash examples/tricks/train_janus_nli.sh
#
# Notable defaults vs the full grpo script:
#   - predictor auxiliary text reward backend selectable via PREDICT_TEXT_REWARD_TYPE={embedding,bleu,nli,none}
#   - structured-key mode: instruction_key=instruction, trajectory_prefix_key=trajectory_1
#   - similarity target = `summary` (gold natural-language summary), via answer_key=summary
#   - trajectory_prefix soft-truncated to last 6000 chars at dataset time
#   - max_prompt_length=8192, truncation=left (keep tail; tail is the agent's most recent action)
#   - small batch / few steps / small rollout group sizes for fast smoke test

set -euo pipefail
set -x

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$ROOT_DIR"

# Ensure we run in the expected conda env.
TARGET_CONDA_ENV=${TARGET_CONDA_ENV:-vllm-fla}
CONDA_SH=${CONDA_SH:-}
if [ "${CONDA_DEFAULT_ENV:-}" != "${TARGET_CONDA_ENV}" ]; then
  if [ -n "${CONDA_SH}" ] && [ -f "${CONDA_SH}" ]; then
    # shellcheck disable=SC1090
    source "${CONDA_SH}"
  elif command -v conda >/dev/null 2>&1; then
    # shellcheck disable=SC1091
    source "$(conda info --base)/etc/profile.d/conda.sh"
  else
    echo "[ERROR] conda not found; cannot activate env '${TARGET_CONDA_ENV}'." >&2
    exit 1
  fi
  conda activate "${TARGET_CONDA_ENV}"
fi

NUM_GPUS=$(nvidia-smi -L 2>/dev/null | grep -c '^GPU' || true)
if ! [[ "$NUM_GPUS" =~ ^[0-9]+$ ]]; then
  NUM_GPUS=0
fi
CPU_CORES=$(getconf _NPROCESSORS_ONLN 2>/dev/null || nproc 2>/dev/null || echo 1)
if ! [[ "$CPU_CORES" =~ ^[0-9]+$ ]] || [ "$CPU_CORES" -le 0 ]; then
  CPU_CORES=1
fi

export DRGRPO=${DRGRPO:-1}
export WANDB_MODE=${WANDB_MODE:-offline}
export TOKENIZERS_PARALLELISM=${TOKENIZERS_PARALLELISM:-true}
# Force Python to ignore user-site packages (~/.local), so we use env-pinned
# torch/vllm wheels and avoid ABI mismatch from globally installed vllm.
export PYTHONNOUSERSITE=${PYTHONNOUSERSITE:-1}
# Some shells set http_proxy=http://127.0.0.1:20808 which routes every Python
# `requests` call through that proxy, returning 503 for our internal vLLM
# embedding / judge endpoints. Force NO_PROXY to always contain our internal
# host, regardless of whether the parent shell already set NO_PROXY to something
# else (or to an empty string). If you need a different list pass
# FORCE_NO_PROXY=... in the env.
export NO_PROXY=${FORCE_NO_PROXY:-localhost,127.0.0.1,10.0.0.0/8,10.102.234.19}
export no_proxy="${NO_PROXY}"

# -----------------------------
# Paths
# -----------------------------
MODEL_PATH=${MODEL_PATH:-Qwen/Qwen3-8B}
# DATA_ROOT points to the "full train minus val" dataset generated by
# scripts/split_val.py without --train_cap (so train_full.json has 6868
# samples = 4 original parts minus the 90 held-out val samples).
# The val.json here is bit-identical to the old janus/ one because
# split_val.py uses the same seed/val_per_group/min_per_class, so metrics
# remain directly comparable across experiments.
DATA_ROOT=${DATA_ROOT:-$ROOT_DIR/data}
TRAIN_FILE=${TRAIN_FILE:-${DATA_ROOT}/train/v5.6_test/train_quick.json}
VAL_FILE=${VAL_FILE:-${DATA_ROOT}/val/v4.27/val.json}
PREDICT_PROMPT=${PREDICT_PROMPT:-$ROOT_DIR/examples/prompts/prediction_prompt.jinja}
JUDGE_PROMPT=${JUDGE_PROMPT:-$ROOT_DIR/examples/prompts/judge_prompt.jinja}
REWARD_FN=${REWARD_FN:-$ROOT_DIR/examples/reward_function/janus_predict_judge.py:compute_score}

if [ ! -f "${TRAIN_FILE}" ] || [ ! -f "${VAL_FILE}" ]; then
  echo "[ERROR] train/val files not found:"
  echo "         TRAIN_FILE=${TRAIN_FILE}"
  echo "         VAL_FILE=${VAL_FILE}"
  echo "       Run scripts/split_val.py first (see header comment)." >&2
  exit 1
fi

for required_file in "${PREDICT_PROMPT}" "${JUDGE_PROMPT}" "${REWARD_FN%%:*}"; do
  if [ ! -f "${required_file}" ]; then
    echo "[ERROR] Required file not found: ${required_file}" >&2
    echo "        Set PREDICT_PROMPT/JUDGE_PROMPT/REWARD_FN explicitly, or add the missing JANUS files." >&2
    exit 1
  fi
done

# -----------------------------
# Group sizes (small for smoke test)
# -----------------------------
PREDICT_ROLL_N=${PREDICT_ROLL_N:-4}
JUDGE_ROLL_N=${JUDGE_ROLL_N:-8}
export caption_rollout_n=${caption_rollout_n:-${CAPTION_ROLLOUT_N:-${PREDICT_ROLL_N}}}

export CAPTION_ROLE_NAME=${CAPTION_ROLE_NAME:-${caption_role_name:-Predictor}}
export SOLVE_ROLE_NAME=${SOLVE_ROLE_NAME:-${solve_role_name:-Judge}}
export caption_role_name=${caption_role_name:-${CAPTION_ROLE_NAME}}
export solve_role_name=${solve_role_name:-${SOLVE_ROLE_NAME}}

# -----------------------------
# Predictor auxiliary text reward during warmup.
#
# Backend selection:
#   PREDICT_TEXT_REWARD_TYPE=embedding|bleu|nli|none
#
# Semantics:
#   use_text_reward_now = backend!=none AND warmup_steps>0 AND current_step<=warmup_steps
#                         AND not validation (unless PREDICT_TEXT_REWARD_IN_VAL=true)
#   blended = (1-λ)·text_reward + λ·utility
#   λ is the UTILITY weight, not the text-reward weight.
#
# NLI defaults to strict mode: initialization/scoring failures abort training
# instead of silently falling back to utility-only rewards.
# -----------------------------
export PREDICT_TEXT_REWARD_TYPE=${PREDICT_TEXT_REWARD_TYPE:-nli}
case "${PREDICT_TEXT_REWARD_TYPE}" in
  embedding|bleu|nli|none) ;;
  *)
    echo "[ERROR] Unsupported PREDICT_TEXT_REWARD_TYPE=${PREDICT_TEXT_REWARD_TYPE}. Use one of embedding|bleu|nli|none." >&2
    exit 1
    ;;
esac
export predict_text_reward_type="${PREDICT_TEXT_REWARD_TYPE}"

if [ "${PREDICT_TEXT_REWARD_TYPE}" = "embedding" ]; then
  export PREDICT_SIMILARITY=true
else
  export PREDICT_SIMILARITY=false
fi
export predict_similarity="${PREDICT_SIMILARITY}"

export PREDICT_REWARD_LAMBDA=${PREDICT_REWARD_LAMBDA:-0.5}
export predict_reward_lambda="${PREDICT_REWARD_LAMBDA}"
export PREDICT_WARMUP_STEPS=${PREDICT_WARMUP_STEPS:-50}
export predict_warmup_steps="${PREDICT_WARMUP_STEPS}"
export PREDICT_TEXT_REWARD_STRICT=${PREDICT_TEXT_REWARD_STRICT:-${predict_text_reward_strict:-true}}
export predict_text_reward_strict="${PREDICT_TEXT_REWARD_STRICT}"
export PREDICT_TEXT_REWARD_IN_VAL=${PREDICT_TEXT_REWARD_IN_VAL:-${predict_text_reward_in_val:-false}}
export predict_text_reward_in_val="${PREDICT_TEXT_REWARD_IN_VAL}"

# BLEU backend (fully local; no extra service/model needed).
export PREDICT_BLEU_MAX_ORDER=${PREDICT_BLEU_MAX_ORDER:-${predict_bleu_max_order:-4}}
export predict_bleu_max_order="${PREDICT_BLEU_MAX_ORDER}"
export PREDICT_BLEU_SMOOTH=${PREDICT_BLEU_SMOOTH:-${predict_bleu_smooth:-true}}
export predict_bleu_smooth="${PREDICT_BLEU_SMOOTH}"

# Local NLI backend (fully offline if the model snapshot is already on disk).
export PREDICT_NLI_MODEL_PATH=${PREDICT_NLI_MODEL_PATH:-${predict_nli_model_path:-}}
export predict_nli_model_path="${PREDICT_NLI_MODEL_PATH}"
export PREDICT_NLI_TOKENIZER_PATH=${PREDICT_NLI_TOKENIZER_PATH:-${predict_nli_tokenizer_path:-${PREDICT_NLI_MODEL_PATH}}}
export predict_nli_tokenizer_path="${PREDICT_NLI_TOKENIZER_PATH}"
# Note: PREDICT_NLI_DEVICE / PREDICT_NLI_BATCH_SIZE defaults are decided by the
# reward-actor placement block below (auto-picks cuda or cpu based on
# REWARD_GPU_SHARE_DEVICE / REWARD_NUM_GPUS). Only mirror user-provided values
# between upper/lower case here.
PREDICT_NLI_DEVICE=${PREDICT_NLI_DEVICE:-${predict_nli_device:-}}
PREDICT_NLI_BATCH_SIZE=${PREDICT_NLI_BATCH_SIZE:-${predict_nli_batch_size:-}}
PREDICT_NLI_CPU_THREADS=${PREDICT_NLI_CPU_THREADS:-${predict_nli_cpu_threads:-}}
export PREDICT_NLI_MAX_LENGTH=${PREDICT_NLI_MAX_LENGTH:-${predict_nli_max_length:-512}}
export predict_nli_max_length="${PREDICT_NLI_MAX_LENGTH}"
export PREDICT_NLI_BIDIRECTIONAL=${PREDICT_NLI_BIDIRECTIONAL:-${predict_nli_bidirectional:-true}}
export predict_nli_bidirectional="${PREDICT_NLI_BIDIRECTIONAL}"
export PREDICT_NLI_EMPTY_SCORE=${PREDICT_NLI_EMPTY_SCORE:-${predict_nli_empty_score:-0.0}}
export predict_nli_empty_score="${PREDICT_NLI_EMPTY_SCORE}"
export PREDICT_NLI_LABEL_MAP=${PREDICT_NLI_LABEL_MAP:-${predict_nli_label_map:-}}
export predict_nli_label_map="${PREDICT_NLI_LABEL_MAP}"
export PREDICT_NLI_LOCAL_FILES_ONLY=${PREDICT_NLI_LOCAL_FILES_ONLY:-${predict_nli_local_files_only:-true}}
export predict_nli_local_files_only="${PREDICT_NLI_LOCAL_FILES_ONLY}"
export PREDICT_NLI_TRUST_REMOTE_CODE=${PREDICT_NLI_TRUST_REMOTE_CODE:-${predict_nli_trust_remote_code:-false}}
export predict_nli_trust_remote_code="${PREDICT_NLI_TRUST_REMOTE_CODE}"

# -----------------------------
# vLLM embedding service (required when PREDICT_SIMILARITY=true).
# function.py reads either upper- or lower-case, export both for safety.
# -----------------------------
export VLLM_EMBEDDING_BASE_URL=${VLLM_EMBEDDING_BASE_URL:-http://10.102.234.19:10034/v1}
export VLLM_EMBEDDING_MODEL=${VLLM_EMBEDDING_MODEL:-Qwen/Qwen3-Embedding-4B}
export VLLM_EMBEDDING_API_KEY=${VLLM_EMBEDDING_API_KEY:-EMPTY}
export VLLM_EMBEDDING_MAX_CONCURRENCY=${VLLM_EMBEDDING_MAX_CONCURRENCY:-256}
export VLLM_EMBEDDING_BATCH_SIZE=${VLLM_EMBEDDING_BATCH_SIZE:-32}
export VLLM_EMBEDDING_TIMEOUT_S=${VLLM_EMBEDDING_TIMEOUT_S:-180}
export VLLM_EMBEDDING_MAX_RETRIES=${VLLM_EMBEDDING_MAX_RETRIES:-3}
export vllm_embedding_base_url=${vllm_embedding_base_url:-${VLLM_EMBEDDING_BASE_URL}}
export vllm_embedding_model=${vllm_embedding_model:-${VLLM_EMBEDDING_MODEL}}
export vllm_embedding_api_key=${vllm_embedding_api_key:-${VLLM_EMBEDDING_API_KEY}}
export vllm_embedding_max_concurrency=${vllm_embedding_max_concurrency:-${VLLM_EMBEDDING_MAX_CONCURRENCY}}
export vllm_embedding_batch_size=${vllm_embedding_batch_size:-${VLLM_EMBEDDING_BATCH_SIZE}}
export vllm_embedding_timeout_s=${vllm_embedding_timeout_s:-${VLLM_EMBEDDING_TIMEOUT_S}}
export vllm_embedding_max_retries=${vllm_embedding_max_retries:-${VLLM_EMBEDDING_MAX_RETRIES}}

# Disable the legacy caption gate (vLLM judge) and discard mode.
export vllm_judge=${vllm_judge:-false}
export discard=${discard:-false}

# -----------------------------
# Reward actor placement (auto-adapts to 4 / 8 / 32 H200 jobs).
#
# Default: local NLI reward workers share the visible actor GPUs via Ray
# runtime_env CUDA_VISIBLE_DEVICES overrides. There is still zero logical GPU
# reservation, so the actor pool keeps all NUM_GPUS and the FSDP batch
# divisibility constraints in fsdp_workers.py remain unchanged. main.py creates
# one reward worker per listed share device when REWARD_NUM_ACTORS is not set,
# so a 32-GPU job computes NLI rewards in parallel across 32 co-resident
# workers. H200's 141 GB has ample headroom for deberta-v3-base (~700 MB)
# alongside the FSDP shard.
#
# Override knobs:
#   REWARD_GPU_SHARE_DEVICE=""    -> disable sharing; if REWARD_NUM_GPUS=0
#                                    and no share device, NLI auto-falls back
#                                    to CPU (because Ray sets
#                                    CUDA_VISIBLE_DEVICES="" for num_gpus=0
#                                    actors, and predict_text_reward.py's
#                                    _resolve_device degrades cuda->cpu when
#                                    torch.cuda.is_available() is False).
#   REWARD_GPU_SHARE_DEVICE=0,1   -> share two devices; reward workers are
#                                    placed round-robin on this list.
#   REWARD_NUM_ACTORS=8           -> use only 8 parallel reward workers even
#                                    when more share devices are listed.
#   REWARD_NUM_GPUS=0.5           -> reserve fractional logical GPUs per
#                                    reward actor instead of sharing. You
#                                    MUST then lower N_GPUS_PER_NODE and
#                                    re-pick ACTOR_GLOBAL_BATCH_SIZE /
#                                    ROLLOUT_BATCH_SIZE so batch math survives
#                                    the smaller actor world.
# -----------------------------
REWARD_NUM_GPUS=${REWARD_NUM_GPUS:-0}
REWARD_NUM_CPUS=${REWARD_NUM_CPUS:-1}
if [ -z "${REWARD_CPU_FALLBACK_ACTORS+x}" ]; then
  REWARD_CPU_FALLBACK_ACTORS=$(awk -v cores="${CPU_CORES}" -v per="${REWARD_NUM_CPUS}" 'BEGIN{if (per<=0) per=1; n=int(cores/per); if (n<1) n=1; if (n>8) n=8; print n}')
fi
export REWARD_CPU_FALLBACK_ACTORS
# Default share-device = all detected GPUs. An explicitly-set empty string
# disables sharing and makes NLI use parallel CPU reward actors.
if [ -z "${REWARD_GPU_SHARE_DEVICE+x}" ]; then
  REWARD_GPU_SHARE_DEVICE=""
  if [ "${NUM_GPUS}" -gt 0 ]; then
    for ((gpu_i = 0; gpu_i < NUM_GPUS; gpu_i++)); do
      if [ -z "${REWARD_GPU_SHARE_DEVICE}" ]; then
        REWARD_GPU_SHARE_DEVICE="${gpu_i}"
      else
        REWARD_GPU_SHARE_DEVICE="${REWARD_GPU_SHARE_DEVICE},${gpu_i}"
      fi
    done
  fi
fi
export REWARD_GPU_SHARE_DEVICE

DEFAULT_REWARD_NUM_ACTORS=1
if [ -n "${REWARD_GPU_SHARE_DEVICE}" ]; then
  IFS=',' read -r -a REWARD_GPU_SHARE_DEVICES <<< "${REWARD_GPU_SHARE_DEVICE}"
  DEFAULT_REWARD_NUM_ACTORS=${#REWARD_GPU_SHARE_DEVICES[@]}
elif [ "${PREDICT_TEXT_REWARD_TYPE}" = "nli" ] \
  && [ "$(awk -v x="${REWARD_NUM_GPUS}" 'BEGIN{print (x>0)?1:0}')" -eq 0 ]; then
  DEFAULT_REWARD_NUM_ACTORS=${REWARD_CPU_FALLBACK_ACTORS}
fi
REWARD_NUM_ACTORS=${REWARD_NUM_ACTORS:-${DEFAULT_REWARD_NUM_ACTORS}}
if ! [[ "${REWARD_NUM_ACTORS}" =~ ^[0-9]+$ ]] || [ "${REWARD_NUM_ACTORS}" -le 0 ]; then
  echo "[ERROR] REWARD_NUM_ACTORS must be a positive integer, got ${REWARD_NUM_ACTORS}." >&2
  exit 1
fi
export REWARD_NUM_ACTORS

if [ -n "${REWARD_GPU_SHARE_DEVICE}" ]; then
  # Shared-GPU mode (default): NLI runs on actor GPU(s) listed in
  # REWARD_GPU_SHARE_DEVICE. No logical GPU reservation; main.py starts
  # REWARD_NUM_ACTORS workers and injects one CUDA_VISIBLE_DEVICES value per
  # worker so torch.cuda sees that worker's assigned device.
  # H200 has 141 GB; deberta-v3-base @ batch=256, max_len=512 fits comfortably
  # alongside the FSDP shard. Larger batch dramatically cuts NLI wall-time
  # during reward eval (the dominant gap between vLLM rollouts).
  PREDICT_NLI_DEVICE=${PREDICT_NLI_DEVICE:-cuda}
  PREDICT_NLI_BATCH_SIZE=${PREDICT_NLI_BATCH_SIZE:-256}
elif [ "$(awk -v x="${REWARD_NUM_GPUS}" 'BEGIN{print (x>0)?1:0}')" -eq 1 ]; then
  # Reserved-GPU mode: caller owns batch-size correctness.
  PREDICT_NLI_DEVICE=${PREDICT_NLI_DEVICE:-cuda}
  PREDICT_NLI_BATCH_SIZE=${PREDICT_NLI_BATCH_SIZE:-256}
else
  # CPU fallback: explicit opt-out via REWARD_GPU_SHARE_DEVICE="", or no
  # detected GPU. Use multiple reward actors and one PyTorch intra-op thread
  # per actor by default to avoid the old single-process CPU bottleneck.
  PREDICT_NLI_DEVICE=${PREDICT_NLI_DEVICE:-cpu}
  PREDICT_NLI_BATCH_SIZE=${PREDICT_NLI_BATCH_SIZE:-16}
  PREDICT_NLI_CPU_THREADS=${PREDICT_NLI_CPU_THREADS:-1}
fi
export PREDICT_NLI_DEVICE
export predict_nli_device="${PREDICT_NLI_DEVICE}"
export PREDICT_NLI_BATCH_SIZE
export predict_nli_batch_size="${PREDICT_NLI_BATCH_SIZE}"
export PREDICT_NLI_CPU_THREADS
export predict_nli_cpu_threads="${PREDICT_NLI_CPU_THREADS}"

N_GPUS_PER_NODE=${N_GPUS_PER_NODE:-${NUM_GPUS}}
if [ "${N_GPUS_PER_NODE}" -le 0 ]; then
  N_GPUS_PER_NODE=1
fi

# -----------------------------
# Length budget for the structured JANUS data
# -----------------------------
MAX_PROMPT_LENGTH=${MAX_PROMPT_LENGTH:-8192}
MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH:-1536}
PREDICT_MAX_TOKENS=${PREDICT_MAX_TOKENS:-512}
TRAJECTORY_PREFIX_MAX_CHARS=${TRAJECTORY_PREFIX_MAX_CHARS:-6000}
TRUNCATION=${TRUNCATION:-left}

# -----------------------------
# Smoke-test scale knobs
# -----------------------------
EXPERIMENT_NAME=${EXPERIMENT_NAME:-janus_nli_v5.6_test_v2}
MAX_STEPS_VALUE=${MAX_STEPS:-300}
ROLLOUT_BATCH_SIZE_VALUE=${ROLLOUT_BATCH_SIZE:-256}
MINI_ROLLOUT_BATCH_SIZE=${MINI_ROLLOUT_BATCH_SIZE:-${ROLLOUT_BATCH_SIZE_VALUE}}
# val.json currently holds ~1500 samples; with VAL_BATCH_SIZE=32 the validation
# loop becomes ~47 driver-side cycles where each cycle has ~25 s of vLLM
# rollout followed by ~4 min of CPU-bound reward+jinja work, dragging GPU duty
# cycle to <10 %. Keep val_batch close to ROLLOUT_BATCH_SIZE so per-cycle
# overhead is amortized over many prompts.
VAL_BATCH_SIZE_VALUE=${VAL_BATCH_SIZE:-256}
JUDGE_VAL_ROLL_N=${JUDGE_VAL_ROLL_N:-${JUDGE_ROLL_N}}

# -----------------------------
# Logging — output goes to both stdout and a log file by default.
# Override with LOG_DIR=... or LOG_FILE=... if you need a custom location.
# -----------------------------
LOG_DIR=${LOG_DIR:-${ROOT_DIR}/log}
mkdir -p "${LOG_DIR}"
LOG_FILE=${LOG_FILE:-${LOG_DIR}/${EXPERIMENT_NAME}_$(date +%Y%m%d_%H%M%S).log}
echo "[train_janus_nli] log file: ${LOG_FILE}"

# -----------------------------
# Batch divisibility sanity check (matches the full grpo script logic)
# -----------------------------
gcd() {
  local a=$1
  local b=$2
  local t
  while [ "$b" -ne 0 ]; do
    t=$((a % b))
    a=$b
    b=$t
  done
  echo "$a"
}

if [ "${PREDICT_ROLL_N}" -le 0 ] || [ "${JUDGE_ROLL_N}" -le 0 ]; then
  echo "[ERROR] PREDICT_ROLL_N and JUDGE_ROLL_N must both be positive integers." >&2
  exit 1
fi

GROUP_GCD=$(gcd "${PREDICT_ROLL_N}" "${JUDGE_ROLL_N}")
BATCH_DIVISOR_STEP=$((JUDGE_ROLL_N / GROUP_GCD))
if [ $((ROLLOUT_BATCH_SIZE_VALUE % BATCH_DIVISOR_STEP)) -ne 0 ]; then
  echo "[ERROR] ROLLOUT_BATCH_SIZE (${ROLLOUT_BATCH_SIZE_VALUE}) must be divisible by ${BATCH_DIVISOR_STEP}." >&2
  exit 1
fi
DEFAULT_ACTOR_GLOBAL_BATCH_SIZE=$((ROLLOUT_BATCH_SIZE_VALUE / BATCH_DIVISOR_STEP))
ACTOR_GLOBAL_BATCH_SIZE=${ACTOR_GLOBAL_BATCH_SIZE:-${DEFAULT_ACTOR_GLOBAL_BATCH_SIZE}}
if [ $((ROLLOUT_BATCH_SIZE_VALUE % ACTOR_GLOBAL_BATCH_SIZE)) -ne 0 ]; then
  echo "[ERROR] ACTOR_GLOBAL_BATCH_SIZE (${ACTOR_GLOBAL_BATCH_SIZE}) must divide ROLLOUT_BATCH_SIZE (${ROLLOUT_BATCH_SIZE_VALUE})." >&2
  exit 1
fi
MERGED_GROUP_FACTOR=$((PREDICT_ROLL_N + JUDGE_ROLL_N))
if [ $(( ((ROLLOUT_BATCH_SIZE_VALUE / ACTOR_GLOBAL_BATCH_SIZE) * MERGED_GROUP_FACTOR) % JUDGE_ROLL_N )) -ne 0 ]; then
  echo "[ERROR] Current batch-size settings are incompatible with merged predict/judge updates." >&2
  exit 1
fi

# -----------------------------
# Auxiliary text reward backend sanity check.
# -----------------------------
echo "[train_janus_nli] predictor text reward backend: ${PREDICT_TEXT_REWARD_TYPE}"
if [ "${PREDICT_TEXT_REWARD_TYPE}" = "embedding" ]; then
  echo "[train_janus_nli] pinging embedding service ${VLLM_EMBEDDING_BASE_URL} ..."
  EMBED_PING_BODY=$(printf '{"model":"%s","input":["healthcheck"]}' "${VLLM_EMBEDDING_MODEL}")
  EMBED_PING_CODE=$(curl -sS --max-time 15 --noproxy '*' \
    -o /tmp/janus_embed_ping.$$ -w "%{http_code}" \
    -X POST "${VLLM_EMBEDDING_BASE_URL}/embeddings" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${VLLM_EMBEDDING_API_KEY}" \
    -d "${EMBED_PING_BODY}" || echo "000")
  if [ "${EMBED_PING_CODE}" != "200" ]; then
    echo "[ERROR] embedding service health check FAILED (HTTP ${EMBED_PING_CODE})." >&2
    echo "        URL:   ${VLLM_EMBEDDING_BASE_URL}" >&2
    echo "        MODEL: ${VLLM_EMBEDDING_MODEL}" >&2
    echo "        body:" >&2
    sed 's/^/          /' /tmp/janus_embed_ping.$$ >&2 || true
    rm -f /tmp/janus_embed_ping.$$
    echo "        Fix the endpoint or set PREDICT_TEXT_REWARD_TYPE=none|bleu|nli." >&2
    exit 1
  fi
  rm -f /tmp/janus_embed_ping.$$
  echo "[train_janus_nli] embedding service OK."
elif [ "${PREDICT_TEXT_REWARD_TYPE}" = "nli" ]; then
  if [ -z "${PREDICT_NLI_MODEL_PATH}" ]; then
    echo "[ERROR] PREDICT_TEXT_REWARD_TYPE=nli but PREDICT_NLI_MODEL_PATH is empty." >&2
    exit 1
  fi
  if [ ! -d "${PREDICT_NLI_MODEL_PATH}" ]; then
    echo "[ERROR] Local NLI model directory not found: ${PREDICT_NLI_MODEL_PATH}" >&2
    exit 1
  fi
  if [ ! -f "${PREDICT_NLI_MODEL_PATH}/config.json" ]; then
    echo "[ERROR] ${PREDICT_NLI_MODEL_PATH}/config.json not found. Please copy a full HF model snapshot." >&2
    exit 1
  fi
  if [ ! -d "${PREDICT_NLI_TOKENIZER_PATH}" ]; then
    echo "[ERROR] Local NLI tokenizer directory not found: ${PREDICT_NLI_TOKENIZER_PATH}" >&2
    exit 1
  fi
  if [ ! -f "${PREDICT_NLI_TOKENIZER_PATH}/tokenizer.json" ] \
    && [ ! -f "${PREDICT_NLI_TOKENIZER_PATH}/vocab.txt" ] \
    && [ ! -f "${PREDICT_NLI_TOKENIZER_PATH}/spiece.model" ] \
    && [ ! -f "${PREDICT_NLI_TOKENIZER_PATH}/sentencepiece.bpe.model" ]; then
    echo "[ERROR] ${PREDICT_NLI_TOKENIZER_PATH} does not look like a complete HF tokenizer snapshot." >&2
    exit 1
  fi
  echo "[train_janus_nli] local NLI model/tokenizer paths OK: ${PREDICT_NLI_MODEL_PATH} / ${PREDICT_NLI_TOKENIZER_PATH}"
  echo "[train_janus_nli] reward actor: num_actors=${REWARD_NUM_ACTORS} num_cpus_each=${REWARD_NUM_CPUS} num_gpus_each=${REWARD_NUM_GPUS} share_device=[${REWARD_GPU_SHARE_DEVICE}] cpu_fallback_actors=${REWARD_CPU_FALLBACK_ACTORS}; nli_device=${PREDICT_NLI_DEVICE} batch_size=${PREDICT_NLI_BATCH_SIZE} cpu_threads=${PREDICT_NLI_CPU_THREADS:-auto}; strict=${PREDICT_TEXT_REWARD_STRICT}; empty_score=${PREDICT_NLI_EMPTY_SCORE}; actor pool n_gpus_per_node=${N_GPUS_PER_NODE} (detected ${NUM_GPUS} physical)."
elif [ "${PREDICT_TEXT_REWARD_TYPE}" = "bleu" ]; then
  echo "[train_janus_nli] using local BLEU reward; no external service/model needed."
else
  echo "[train_janus_nli] auxiliary text reward disabled; using utility-only caption reward."
fi

if [ "${PREDICT_WARMUP_STEPS}" -ge "${MAX_STEPS_VALUE}" ]; then
  echo "[WARN] PREDICT_WARMUP_STEPS (${PREDICT_WARMUP_STEPS}) >= MAX_STEPS (${MAX_STEPS_VALUE}); the auxiliary text reward stays active for the whole run." >&2
fi

# -----------------------------
# Launch
# -----------------------------
python3 -m verl.trainer.main \
  config=examples/config.yaml \
  data.train_files="$TRAIN_FILE" \
  data.val_files="$VAL_FILE" \
  data.prompt_key=instruction \
  data.instruction_key=instruction \
  data.trajectory_prefix_key=trajectory_1 \
  data.trajectory_prefix_max_chars=${TRAJECTORY_PREFIX_MAX_CHARS} \
  data.answer_key=summary \
  data.solve_ground_truth_key=label \
  data.image_dir=null \
  data.val_image_dir=null \
  data.caption_prompt="$PREDICT_PROMPT" \
  data.solve_prompt="$JUDGE_PROMPT" \
  data.solve_use_images=false \
  data.caption_use_question=true \
  data.truncation=${TRUNCATION} \
  data.max_prompt_length=${MAX_PROMPT_LENGTH} \
  data.max_response_length=${MAX_RESPONSE_LENGTH} \
  data.caption_max_tokens=${PREDICT_MAX_TOKENS} \
  data.rollout_batch_size=${ROLLOUT_BATCH_SIZE_VALUE} \
  data.mini_rollout_batch_size=${MINI_ROLLOUT_BATCH_SIZE} \
  data.val_batch_size=${VAL_BATCH_SIZE_VALUE} \
  data.filter_overlong_prompts=${FILTER_OVERLONG_PROMPTS:-false} \
  algorithm.adv_estimator=grpo \
  algorithm.disable_kl=${DISABLE_KL:-true} \
  algorithm.use_kl_loss=${USE_KL_LOSS:-false} \
  worker.actor.model.model_path="$MODEL_PATH" \
  worker.actor.global_batch_size=${ACTOR_GLOBAL_BATCH_SIZE} \
  worker.rollout.n=${JUDGE_ROLL_N} \
  worker.rollout.temperature=${TEMPERATURE:-1.0} \
  worker.rollout.top_p=${TOP_P:-1.0} \
  worker.rollout.tensor_parallel_size=${TENSOR_PARALLEL_SIZE:-1} \
  worker.rollout.val_override_config.n=${JUDGE_VAL_ROLL_N} \
  worker.reward.reward_function="$REWARD_FN" \
  worker.reward.reward_function_kwargs.format_weight=0.1 \
  worker.reward.num_cpus=${REWARD_NUM_CPUS} \
  worker.reward.num_gpus=${REWARD_NUM_GPUS} \
  worker.reward.enable_solver_update_sampling=true \
  worker.reward.solver_update_ratio=1 \
  worker.reward.enable_solver_update_group_filter=true \
  worker.reward.solver_update_filter_key=accuracy \
  worker.reward.enable_solver_update_random_sampling=true \
  worker.reward.caption_reward_key=accuracy \
  trainer.project_name=${PROJECT_NAME:-easy_r1_janus} \
  trainer.experiment_name="$EXPERIMENT_NAME" \
  trainer.logger='["file","wandb"]' \
  trainer.nnodes=${NNODES:-1} \
  trainer.n_gpus_per_node=${N_GPUS_PER_NODE} \
  trainer.total_epochs=${TOTAL_EPOCHS:-1} \
  trainer.max_steps=${MAX_STEPS_VALUE} \
  trainer.val_freq=${VAL_FREQ:-50} \
  trainer.val_before_train=${VAL_BEFORE_TRAIN:-false} \
  trainer.save_freq=${SAVE_FREQ:-${VAL_FREQ:-50}} \
  trainer.save_limit=${SAVE_LIMIT:-2} \
  trainer.save_best_checkpoint=${SAVE_BEST_CHECKPOINT:-true} \
  2>&1 | tee "${LOG_FILE}"

echo "[train_janus_nli] done. log file: ${LOG_FILE}"
